"use client";
import Head from "next/head";
import AllTodos from "~/components/allTodos";
import CreateTodo from "~/components/createTodo";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import UserTodos from "~/components/userTodos";

export default function Home() {
  const { isSignedIn } = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {!isSignedIn && (
          <div className="flex flex-col items-center text-white">
            <p className="mb-4 text-2xl font-semibold">All Todos</p>
            <AllTodos />
            <div className="w-fit rounded-lg bg-black px-2 py-1 text-green-600">
              <SignInButton />
            </div>
          </div>
        )}
        {isSignedIn && (
          <div className="flex flex-col items-center gap-2 text-white">
            <UserTodos />
            <CreateTodo />
            <div className="w-fit rounded-lg bg-black px-2 py-2 text-red-600">
              <SignOutButton />
            </div>
          </div>
        )}
      </main>
    </>
  );
}
